#!/bin/bash
SNAPSHOT=$2
REGION=$1
. ./identity
curl -s \
-H "Content-Type: application/json" \
-H "X-Auth-Token: $APITOKEN" \
-D cb_snapshot_show.txt \
https://$REGION.blockstorage.api.rackspacecloud.com/v1/$DDI/snapshots/$SNAPSHOT | python -m json.tool
